close_when_open = true          # close walker when invoking while already opened
selection_wrap = false          # wrap list if at bottom or top
global_argument_delimiter = "#" # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
keep_open_modifier = "shift"    # won't close on activation, but rather select the next item in the list
exact_search_prefix = "'"       # disable fuzzy searching

[keybinds]
close = "esc"
next = "down"
previous = "up"
toggle_exact = "ctrl e"

[providers]
default = [
  "desktopapplications",
  "calc",
  "runner",
  "menus",
  "websearch",
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[providers.calc]
copy = "enter"
save = "ctrl s"
delete = "ctrl d"

[providers.websearch]
search = "enter"

[providers.providerlist]
activate = "enter"

[providers.clipboard]
time_format = "dd.MM. - hh:mm"
copy = "enter"
delete = "ctrl d"

[providers.desktopapplications]
start = "enter"

[providers.files]
open = "enter"
open_dir = "ctrl enter"
copy_path = "ctrl shift C"
copy_file = "ctrl c"

[providers.runner]
start = "enter"
start_terminal = "shift enter"

[providers.symbols]
copy = "enter"

[providers.menus]
activate = "enter"
